- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_directory
  when: tmp_folder is not defined
  check_mode: false

- name: "Create temporary folder {{ tmp_folder }}"
  ansible.builtin.file:
    path: "{{ tmp_folder }}"
    state: directory
    mode: 0644
  when: tmp_folder is defined

- name: Set global variables
  ansible.builtin.set_fact:
    tmp_folder: "{{ tmp_folder | default(temp_directory.path) }}"
    images_uploaded: [] # Storing results during the run
