- name: Check for previous public image
  openstack.cloud.image_info:
    image: "{{ display_name }} - Latest"
    properties:
      uploaded_by: Image Uploader
  register: latest_image_in_glance
  changed_when: latest_image_in_glance.image

- name: Set previous latest image to community and change its name
  openstack.cloud.image: # noqa no-handler
    id: "{{ latest_image_in_glance.image.id }}"
    name: "{{ display_name }} - Latest"
    properties:
      visibility: community
      name: "{{ display_name }} - {{ latest_image_in_glance.image.description }}"
    protected: true
  when: latest_image_in_glance.changed

- name: Set new image to public and protected
  openstack.cloud.image: # noqa no-handler
    id: "{{ image.id }}"
    name: "{{ image.name }}"
    properties:
      visibility: public
      name: "{{ display_name }} - Latest"
    protected: true
  when: uploaded_image.changed

- name: Add new image to report
  ansible.builtin.set_fact: # noqa no-handler jinja
    images_uploaded: "{{ images_uploaded + [{'title': report_item.title, 'value': report_item.value}] }}"
  loop_control:
    loop_var: report_item
  with_items:
    - { "title": "{{ display_name }} - Latest", "value": "{{ image.id }}" }
  when: uploaded_image.changed
